# @package _global_

train_dataset:
  _target_: datasets.classification.cifar10.CIFAR10
  root: ${env:DATA_DIR}/cifar10
  train: true
  download: true

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  pin_memory: true
  num_workers: 8

val_dataset:
  _target_: datasets.classification.cifar10.CIFAR10
  root: ${env:DATA_DIR}/cifar10
  train: false
  download: true

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  pin_memory: true
  num_workers: 8

epochs: 200

optim:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [60, 120, 160]
  gamma: 0.2

model:
  _target_: models.wide_resnet.wide_resnet_28x10
  num_classes: 10
