# @package _global_

train_dataset:
  _target_: datasets.classification.imagenet.ImageNet
  root: "${env:DATA_DIR}/imagenet"
  split: "train"

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  pin_memory: true
  num_workers: 8

val_dataset:
  _target_: datasets.classification.imagenet.ImageNet
  root: "${env:DATA_DIR}/imagenet"
  split: "val"

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  pin_memory: true
  num_workers: 8

epochs: 110

optim:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  nesterov: true

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [30, 70]
  gamma: 0.1

model:
  _target_: torchvision.models.resnet50
  num_classes: 1000
  pretrained: false
